# esAPI uses the first host in the Elasticsearch group to check status
# To use HAProxy as the API endpoint, uncomment the line below and comment the line referencing groups['elasticsearch']
# esAPI: "https://{{ groups['haproxy'][0] }}:9200"
esAPI: "https://{{ groups['elasticsearch'][0] }}:9200"

# Basic config variables
esVersion: 8.12.2
elasticPassword: "elastic"
kibanaPassword: "temp1234$$"
logstashPassword: "temp5678$$"
beatsPassword: "temp8901$$"
monitorPassword: "temp2345$$"

# Set rollingRestart to false if recovering from complete failure i.e. all nodes offline
# This will prevent nodes from waiting for the cluster to become green
rollingRestart: false

# Define custom repo path if not using Elastic's public repo
# esRepoPath:

# Define certs, keys, and CA. These should be in certifcates directory
# 1 cert/key pair per host and 1 CA for the cluster is standard
# Can also support wildcard or multi-SAN certificates
hostCert: "{{ inventory_hostname }}.crt"
hostKey: "{{ inventory_hostname }}.key"
hostCA: "ca.crt"
