# Module: haproxy
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-haproxy.html

- module: haproxy
  metricsets:
   - info
   - stat
  period: 10s
  hosts: ["unix:///var/lib/haproxy/stats"]