---
- name: Restart Filebeat
  ansible.builtin.service:
    name: filebeat
    state: restarted
    enabled: true
  become: true

- name: Remove Filebeat Keystore
  ansible.builtin.file:
    path: /etc/filebeat/filebeat.keystore
    state: absent
  become: true
  listen: Rebuild Keystore

- name: Create the Filebeat Keystore
  command: filebeat keystore create
  args:
    chdir: /usr/share/filebeat/bin/
    creates: /etc/filebeat/filebeat.keystore
  become: true
  listen: Rebuild Keystore

- name: Add Setup Password to Keystore
  command: filebeat keystore add --force --stdin {{ item.name }}
  args:
    chdir: /usr/share/filebeat/bin/
    stdin: "{{ item.pass }}"
  no_log: true
  loop:
    - name: monitor_password
      pass: "{{ monitorPassword }}"
    - name: beats_password
      pass: "{{ beatsPassword }}"
    - name: elastic_password
      pass: "{{ elasticPassword }}"
  notify: Restart Filebeat
  become: true
  listen: Rebuild Keystore