---
- name: Reload sysctl
  ansible.builtin.command:
    cmd: "sysctl -p"
  listen: "sysctl changed"
  become: true

- name: Reload systemd
  ansible.builtin.command:
    cmd: "systemctl daemon-reload"
  listen: "Service changed"
  become: true

- name: Delete the Elasticsearch Keystore
  ansible.builtin.file:
    path: /etc/elasticsearch/elasticsearch.keystore
    state: absent
  become: true
  listen: Rebuild Keystore

- name: Create the Elasticsearch Keystore
  ansible.builtin.command: "/usr/share/elasticsearch/bin/elasticsearch-keystore create"
  args:
    creates: "/etc/elasticsearch/elasticsearch.keystore"
  become: true
  listen: Rebuild Keystore

- name: Set Bootstrap Password
  ansible.builtin.command: /usr/share/elasticsearch/bin/elasticsearch-keystore add -f bootstrap.password
  no_log: false
  args:
    stdin: "{{ elasticPassword }}"
  become: true
  listen: Rebuild Keystore

- name: Set keystore ownership
  ansible.builtin.file:
    path: /etc/elasticsearch/elasticsearch.keystore
    group: elasticsearch
    mode: '0670'
  become: true
  listen: Rebuild Keystore

- name: Add hosts to restart groups
  ansible.builtin.add_host:
    hostname: "{{ item }}"
    groups:
      - "elasticsearch_{{ hostvars[item]['esGroup'] }}_{{ hostvars[item]['esNeedsRestart'] }}"
  loop: "{{ play_hosts }}"
  listen:
    - Rebuild Keystore
    - Restart Elasticsearch
